on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 7.4

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v2
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
            - name: Install php-cs-fixer
              run: composer install --working-dir=tools/php-cs-fixer
            - name: Run tests
              run: ./vendor/bin/phpunit
            - name: Run PHPStan
              run: ./vendor/bin/phpstan
            - name: Run Psalm
              run: ./vendor/bin/psalm
            - name: Run PHP-CS-Fixer in src
              run: ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src
            - name: Run PHP-CS-Fixer in tests
              run: ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix tests
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                   commit_message: Apply php-cs-fixer changes
